# Generated by Django 4.2.1 on 2024-04-12 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BuchererItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.watch')),
            ],
        ),
    ]
