# Generated by Django 4.2.1 on 2024-04-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_watch_reference_buchereritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchereritem',
            name='item_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buchereritem',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='watch',
            name='brecelet',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='dial',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
