# Generated by Django 4.2.1 on 2024-04-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_buchereritem_item_number_buchereritem_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchereritem',
            name='item_number',
            field=models.CharField(max_length=20),
        ),
    ]
