# Generated by Django 4.2.1 on 2024-04-23 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_buchereritem_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchereritem',
            name='dial',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buchereritem',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.watchitem'),
        ),
        migrations.AddField(
            model_name='buchereritem',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buchereritem',
            name='size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buchereritem',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
